const Mongoose=require("mongoose");
const ItemSchema=Mongoose.Schema(
    {
      itemname :{
        type:String,
        required:true
      }, 
      unit:{
        type:Number,
        required:true
      },
      dimension:{
        type:String,
        required:true
      },
      weight:{
        type:String,
        required:true
      },
      mfacturer:{
        type:String,
        required:true
      },
      brand:{
        type:String,
        required:true
      },
      sprice:{
        type:String,
        required:true
      },
      cprice:{
        type:String,
        required:true
      },
      description:{
        type:String,
        required:true
      },
      ostock:{
        type:String,
        required:true
      },
      reorderpoint:{
        type:String,
        required:true
      },
      pvendor:{
        type:String,
        required:true
      },
      photo:{
        type:String,
        required:true
      },
      date:{
        type:Date
        
      }
    }
);
const ItemModel=Mongoose.model("items",ItemSchema);
module.exports=ItemModel;